### ISSUE TITLE
Auto and Set will not update the Steps bars

### ISSUE THREAD

**Issue by nuclearsugar** [robenkleene/sidewinder#11]
Beautiful device!

Whenever I adjust the Steps knob, the steps bars are not updating (with Auto enabled). It also will not update when I click the Set button.

I'm using Ableton Live 10.1.9

**Comment by robenkleene** [comment]
Hi @nuclearsugar, thanks for the kind words! How are you running Sidewinder? Did you move `Sidewinder.amxd` into `Ableton/User Library/Presets/MIDI Effects/Max MIDI Effect/`, and then add the device to a track in Ableton Live via the device browser?

(The specifics of this shouldn't matter, the important thing is just to be using the `Sidewinder.amxd` file which is the entirely self-contained version of the patch.)

**Comment by nuclearsugar** [comment]
Indeed, I tried installing `Sidewinder.amxd` to that location. I tested both the [maxforlive](https://maxforlive.com/library/device/5794/sidewinder) and [github](https://github.com/robenkleene/sidewinder/tree/master/max-for-live) AMXD files just to be sure. Let me know if I can test anything further.

**Comment by robenkleene** [comment]
What OS are you on? macOS or Windows?

Do you have any experience with Max itself? The first thing to check is whether Max is printing an error message to the console.

To do this, I'd try opening `Sidewinder Module.maxpat` in Max directly (i.e., without running Ableton Live). Here's a screenshot of what to look for:

![debugging](https://user-images.githubusercontent.com/1058778/78054061-7de52000-734f-11ea-9074-76da6168f6e7.png)

If you aren't seeing any errors there, you could try opening `Sidewinder Rack.maxpat` and checking there too.

**Comment by nuclearsugar** [comment]
I'm using the version of Max that is included within Ableton Live Suite 10.1.9. 

I downloaded this repo and then opened `Sidewinder Module.maxpat`. I saw the following errors.

![Screen Shot 2020-03-31 at 11 02 35 PM](https://user-images.githubusercontent.com/8218211/78095087-19a07b80-73a4-11ea-9775-44b10662cc9b.png)

**Comment by nuclearsugar** [comment]
Also I opened `Sidewinder.amxd` and tried editing it in Max. It pinpointed the errors with perhaps more verbosity. 

![Screen Shot 2020-03-31 at 10 56 04 PM](https://user-images.githubusercontent.com/8218211/78095223-684e1580-73a4-11ea-8477-192d933ce536.png)
![Screen Shot 2020-03-31 at 10 56 08 PM](https://user-images.githubusercontent.com/8218211/78095226-68e6ac00-73a4-11ea-830e-024a65b9df2a.png)
![Screen Shot 2020-03-31 at 10 56 27 PM](https://user-images.githubusercontent.com/8218211/78095230-697f4280-73a4-11ea-8e2c-8544ff55e6e8.png)

**Comment by robenkleene** [comment]
Awesome, I pushed an update that hopefully fixes this (both here and on Max for Live), please give it a try if you don't mind and let me know if it works for you.

For the record: The first errors, when just opening `Sidewinder Module.maxpat`, are probably  because the Sidewinder folder isn't in one of your Max Project Search Paths. I think if you're opening a Max project that's broken up into different files, then it has to be in a folder off your Max Project Search Path. There's some [Cycling '74 documentation](https://docs.cycling74.com/max8/vignettes/projects_searchpath) into how this works, but I'm pretty sure this is the setting in preferences for the root path:

![max](https://user-images.githubusercontent.com/1058778/78181918-261fe500-7433-11ea-84e1-0c0a15bccb09.png)

But when opening the `amxd` file, that shouldn't matter, because the `amxd` file is frozen, and freezing packages all of the assets together. So the reason you're getting a different error there, is because I packaged some, but not all, of the JavaScript files into the `amxd`. And, the reason I didn't notice, is because the Sidewinder folder *is* in one of my Max Search Paths, so when the JavaScript file was missing from the `amxd` file on my end, it was just picking up the file from the search path... whew, confusing.

At any rate, if this version still has problems please let me know, and thanks for excellent screenshots!

**Comment by nuclearsugar** [comment]
That fixed it! Happy to help. 

Thanks for the info.
